
name: Download data
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 6,8,10,12,14,16,18 * * *'

jobs:
  harvest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Download info
      run: |
        timestamp=$(date +"%Y-%m-%d_%T")
        wget -O data/${timestamp}.geojson "https://www.turistickysemafor.sk/wms?service=WMS&version=1.1.1&request=GetFeatureInfo&exceptions=application%2Fjson&id=touristics_localities__5&layers=touristics_localities&query_layers=touristics_localities&x=1&y=1&height=3&width=3&srs=EPSG:3857&bbox=1875771,6063684,2514287,6380943&feature_count=1000&info_format=application%2Fjson&ENV=mapstore_language:en"

    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: Turista
        author_email: turista@turista.com
